### ISSUE TITLE
P4实际左右和观测b报错

### ISSUE THREAD

**Issue by dacheng26** [pipirapira/NiNiTechnology#12]
https://www.bilibili.com/video/av78083721/
视频14：30左右
我是红绿小黑，报的是大黑大黑，B点向北。
另观测a的C点左右似乎有问题，如果以A点为12点，左右是反的

**Comment by RyanDarkness** [comment]
关于α的左右，大概确实是错了。
β的话你实际是报了两种，红绿小黑B点向北跟大黑大黑B点不动。这种情况理论不会发生，应该是设定β开始后100ms读取日志作判定时候，你卡了导致所有8个影子的日志条目没有加载好就判定了第一次。目前还没有其他人报告过类似现象。

**Comment by pipirapira** [comment]
感谢提供错误案例！左右报反的问题已修复。
另，β的问题可能是由于网络延迟较高，超出了观测时间。在新版本中将100毫秒的观测时间延长到200毫秒，这在大部分国内玩家的延迟可接受的范围内，β的错误率将减低，但仍然不排除由于加速器原因导致丢包时误判的可能性。如果您经常发生该问题，请做好独立判断的准备。
