### ISSUE TITLE
有考虑根据云玩家团的走位更新一下二运麻将走位提示吗

### ISSUE THREAD

**Issue by heroxsj** [pipirapira/NiNiTechnology#13]
https://bbs.nga.cn/read.php?tid=19507584
就是这个帖子

**Comment by heroxsj** [comment]
感觉这个容错比1A的高多了，而且简单易懂一些

**Comment by pipirapira** [comment]
麻将打法很多，目前TTS在这方面能提供的帮助相当有限。等标准统一以后，我们会尽可能采纳最好的方案来设计。
