### ISSUE TITLE
科技标点出现一点小问题

### ISSUE THREAD

**Issue by ouchaojun1** [pipirapira/NiNiTechnology#15]
科技在绝巴哈P2俯冲的时候不能正常标点，但是换另一台机器就可以正常标点 请问我是缺少了什么插件吗

**Comment by pipirapira** [comment]
请下载安装Paisley Park国服的对应版本，并正确开启端口。

**Comment by ouchaojun1** [comment]
Paisley Park CN 1.4.0也已经启动好了，测试连接也没问题 只是P2俯冲那边不会自动标点。。

**Comment by pipirapira** [comment]
可以尝试手动使用paisley park标点，如果不能成功，是paisley park的问题。如果能够成功，但仍然不工作，请将插件日志贴出来或者发送给我以确定问题。
在你打开插件时，会看到如下信息：
正在初始化...
日志文件：C:\Users\Administrator\AppData\Roaming\anoyetta\ACT\ACT.BahamutAnalyser.log
这就是日志文件的地址。如果你能找到当时无法工作的日志文件，请将它尽可能完整地发送给我。

**Comment by ouchaojun1** [comment]
[ACT.BahamutAnalyser.log](https://github.com/pipirapira/NiNiTechnology/files/3934884/ACT.BahamutAnalyser.log)
这边是我刚打的一次，很奇怪为什么会无法连接到远程服务器

**Comment by pipirapira** [comment]
您好，日志显示的错误是无法连接到远程服务器。这通常是由于没有连接到Paisley Park端口导致的。
1.请检查Paisley Park中Port的设置和插件内“场地标点”选项卡的Port的设置一致。例如全部设为2005。
2.点击Paisley Park里的Start按钮开启端口。
3.如果你勾上Stop后面的选项框，Paisley Park每次启动会自动开启端口。
4.点击插件“测试连接”按钮，确认“连接成功”提示以后继续使用。

**Comment by ouchaojun1** [comment]
但是我在科技里面测试的话是显示连接成功 端口的话我是设置成了15464

**Comment by pipirapira** [comment]
可能有其它程序占用了这个端口，可以改变端口号再次测试。根据您的日志，插件始终没有正常连接到端口。

**Comment by ouchaojun1** [comment]
![image](https://user-images.githubusercontent.com/58506741/70372356-bf713b80-1918-11ea-80de-a66b88145c03.png)
查找端口使用情况没发现什么异常

**Comment by ouchaojun1** [comment]
我这里只有windows自带的defender
