### ISSUE TITLE
E4S,触发器相关

### ISSUE THREAD

**Issue by Gxyloj** [pipirapira/NiNiTechnology#4]
黄标橙标和蓝点名的提示是怎么使用的？我还在别的视频里还看到有左右拳拆地板安全点播报，用的好像是同一个时间轴，谢谢

**Comment by pipirapira** [comment]
你好，Timeline时间轴只能预报固定技能，随机性技能是使用Triggernometry插件加载TTS触发器进行即时播报的哦。请下载Triggernometry触发器插件和E4S对应的xml文件，在插件中点击Import按钮加载xml文件。

**Comment by Gxyloj** [comment]
> 你好，Timeline时间轴只能预报固定技能，随机性技能是使用Triggernometry插件加载TTS触发器进行即时播报的哦。请下载Triggernometry触发器插件和E4S对应的xml文件，在插件中点击Import按钮加载xml文件。

感谢解答 我试一下

**Comment by Gxyloj** [comment]
> 你好，Timeline时间轴只能预报固定技能，随机性技能是使用Triggernometry插件加载TTS触发器进行即时播报的哦。请下载Triggernometry触发器插件和E4S对应的xml文件，在插件中点击Import按钮加载xml文件。

Triggernometry触发器，九宫格安全点和穿的倒计时无法正常工作，P2开始的左右拳和拆地板都可以正常播报。使用的是汉化客户端

**Comment by pipirapira** [comment]
> > 你好，Timeline时间轴只能预报固定技能，随机性技能是使用Triggernometry插件加载TTS触发器进行即时播报的哦。请下载Triggernometry触发器插件和E4S对应的xml文件，在插件中点击Import按钮加载xml文件。
> 
> Triggernometry触发器，九宫格安全点和穿的倒计时无法正常工作，P2开始的左右拳和拆地板都可以正常播报。使用的是汉化客户端

感谢反馈，问题已修复，请下载最新版TTS。

**Comment by Gxyloj** [comment]
> > > 你好，Timeline时间轴只能预报固定技能，随机性技能是使用Triggernometry插件加载TTS触发器进行即时播报的哦。请下载Triggernometry触发器插件和E4S对应的xml文件，在插件中点击Import按钮加载xml文件。
> > 
> > 
> > Triggernometry触发器，九宫格安全点和穿的倒计时无法正常工作，P2开始的左右拳和拆地板都可以正常播报。使用的是汉化客户端
> 
> 感谢反馈，问题已修复，请下载最新版TTS。

非常感谢
