### ISSUE TITLE
关于占星发卡错乱问题及triggernometry队员排序问题的建议

### ISSUE THREAD

**Issue by SheldonHoo233** [pipirapira/NiNiTechnology#47]
可能占星发卡该问题存在过几个版本，由于近期了解了一些触发器的原理，想提供一些（不确定是否一定可行的）想法。
针对国服（只是因为本人没有玩过国际服），目前占星发卡错乱主要原因在于triggernometry给出的函数${_ffxivparty[1].order}并非完全按照小队队员排序。占星发卡系统的逻辑应该是没有问题的，但发卡的order并不对应游戏中的排序。
所以有个初步的想法，可以将${_ffxivparty[1].name}与真正游戏内的玩家排序对应起来。triggernometry给了jobid与玩家id两个参数。游戏中的队员排序，应该是除去本人，其他的先对职业进行排序，同职业玩家id越大越前面（仅看到过国际服玩家这么说）。

使用者需要按照他自己的习惯，给不同的职业一个顺序，比如剑术师赋值job[1]=1，骑士赋值job[?]=2……一直到青魔法师job[36]=36。
然后做一个触发器，设定一个i从1开始，并重复触发到8。
i=1时
party.order[1]=1（因为自己永远是一位，不进行排序），party.order[2]=2，party.order[3]=2……party.order[8]=2（其他人从2位开始排序）
i=2-8时，
（1）如果职业序号比当前的大，则序号+1。
若${lvar:job[${_ffxivparty[2].jobid}]}>${lvar:job[${_ffxivparty[i].jobid}]}，则party.order[2]=${lvar:party.order[2]}+1
（2）如果职业序号相同，且id小，则序号+1，
若${lvar:job[${_ffxivparty[2].jobid}]}=${lvar:job[${_ffxivparty[i].jobid}]}且id[2]<id[i]，则party.order[2]=${lvar:party.order[2]}+1
……
（14）一直从2比较到8。
这样的话，应该${lvar:party.order[${_ffxivparty[n].order}]}应该就可以正确表达游戏中的玩家序号了吧，从而使用F1~F12正确选对玩家。
上述完全是云想法，可能有许多错误的猜想和考虑不周的地方，还请不吝指正。
另外，占星发卡的想法非常好，感谢开发。

**Comment by SheldonHoo233** [comment]
目前尝试这样解决：
（1）导入两个触发器，一个是“设定FFXIV职业顺序”，另一个是“队员排序”。（这两个可以在切换区域时候触发。对触发器不是很了解的朋友，可以保留触发器“切换区域”，了解运作原理的朋友，可以自行安排。）
（2）键位设置中，如果习惯用F1-F8选中队友，可以把原本的改成，向最终幻想XIV发送
${numeric:${lvar:party_order[${var:card_target_party_id}]}+111}
如果习惯用F5-F12选中队友，则改成
${numeric:${lvar:party_order[${var:card_target_party_id}]}+115}
其余不变。
（3）题外话：所以说，绕了半天只是为了达到这个目的——这个变量${lvar:party_order[${_ffxivparty[玩家姓名].order}]}，设计上等于游戏中的他的序号。
（4）测试次数不多，似乎没什么问题，如果发现有问题，请回复我。

以下是需要额外导入的触发器：
`<?xml version="1.0"?>
<TriggernometryExport Version="1">
  <ExportedFolder Id="53876bb0-466a-424f-8f11-1acf3618a397" Name="队员排序功能" Enabled="true">
    <Folders />
    <Triggers>
      <Trigger Enabled="true" Sequential="True" Name="队员排序" Id="2dfe2e95-ca7b-4d51-8fb0-7cd9409a2286" RegularExpression="Party sort(?&lt;i&gt;[1-8]):(?&lt;j&gt;[2-8])">
        <Actions>
          <Action OrderNumber="1" ListVariableName="party_order" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="true" Grouping="And">
              <ConditionSingle Enabled="true" ExpressionL="${i}" ExpressionTypeL="Numeric" ExpressionR="1" ExpressionTypeR="Numeric" ConditionType="NumericEqual" />
            </Condition>
            <Conditions />
          </Action>
          <Action OrderNumber="2" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="party_order" ListVariableExpression="1" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="true" Grouping="And">
              <ConditionSingle Enabled="true" ExpressionL="${i}" ExpressionTypeL="Numeric" ExpressionR="1" ExpressionTypeR="Numeric" ConditionType="NumericEqual" />
            </Condition>
            <Conditions />
          </Action>
          <Action OrderNumber="3" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="party_order" ListVariableExpression="2" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="true" Grouping="And">
              <ConditionSingle Enabled="true" ExpressionL="${i}" ExpressionTypeL="Numeric" ExpressionR="1" ExpressionTypeR="Numeric" ConditionType="NumericEqual" />
            </Condition>
            <Conditions />
          </Action>
          <Action OrderNumber="4" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="party_order" ListVariableExpression="2" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="true" Grouping="And">
              <ConditionSingle Enabled="true" ExpressionL="${i}" ExpressionTypeL="Numeric" ExpressionR="1" ExpressionTypeR="Numeric" ConditionType="NumericEqual" />
            </Condition>
            <Conditions />
          </Action>
          <Action OrderNumber="5" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="party_order" ListVariableExpression="2" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="true" Grouping="And">
              <ConditionSingle Enabled="true" ExpressionL="${i}" ExpressionTypeL="Numeric" ExpressionR="1" ExpressionTypeR="Numeric" ConditionType="NumericEqual" />
            </Condition>
            <Conditions />
          </Action>
          <Action OrderNumber="6" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="party_order" ListVariableExpression="2" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="true" Grouping="And">
              <ConditionSingle Enabled="true" ExpressionL="${i}" ExpressionTypeL="Numeric" ExpressionR="1" ExpressionTypeR="Numeric" ConditionType="NumericEqual" />
            </Condition>
            <Conditions />
          </Action>
          <Action OrderNumber="7" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="party_order" ListVariableExpression="2" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="true" Grouping="And">
              <ConditionSingle Enabled="true" ExpressionL="${i}" ExpressionTypeL="Numeric" ExpressionR="1" ExpressionTypeR="Numeric" ConditionType="NumericEqual" />
            </Condition>
            <Conditions />
          </Action>
          <Action OrderNumber="8" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="party_order" ListVariableExpression="2" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="true" Grouping="And">
              <ConditionSingle Enabled="true" ExpressionL="${i}" ExpressionTypeL="Numeric" ExpressionR="1" ExpressionTypeR="Numeric" ConditionType="NumericEqual" />
            </Condition>
            <Conditions />
          </Action>
          <Action OrderNumber="9" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="party_order" ListVariableExpression="2" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="true" Grouping="And">
              <ConditionSingle Enabled="true" ExpressionL="${i}" ExpressionTypeL="Numeric" ExpressionR="1" ExpressionTypeR="Numeric" ConditionType="NumericEqual" />
            </Condition>
            <Conditions />
          </Action>
          <Action OrderNumber="10" ListVariableOp="Set" ListVariableExpressionType="Numeric" ListVariableName="party_order" ListVariableExpression="${numeric:${lvar:party_order[${i}]}+1}" ListVariableIndex="${i}" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="true" Grouping="And">
              <ConditionSingle Enabled="true" ExpressionL="${lvar:job_order[${_ffxivparty[${i}].jobid}]}" ExpressionTypeL="Numeric" ExpressionR="${lvar:job_order[${_ffxivparty[${j}].jobid}]}" ExpressionTypeR="Numeric" ConditionType="NumericGreater" />
              <ConditionSingle Enabled="true" ExpressionL="${i}" ExpressionTypeL="Numeric" ExpressionR="1" ExpressionTypeR="Numeric" ConditionType="NumericNotEqual" />
            </Condition>
            <Conditions />
          </Action>
          <Action OrderNumber="11" ListVariableOp="Set" ListVariableExpressionType="Numeric" ListVariableName="party_order" ListVariableExpression="${numeric:${lvar:party_order[${i}]}+1}" ListVariableIndex="${i}" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="true" Grouping="And">
              <ConditionSingle Enabled="true" ExpressionL="${lvar:job_order[${_ffxivparty[${i}].jobid}]}" ExpressionTypeL="Numeric" ExpressionR="${lvar:job_order[${_ffxivparty[${j}].jobid}]}" ExpressionTypeR="Numeric" ConditionType="NumericEqual" />
              <ConditionSingle Enabled="true" ExpressionL="${numeric:hex2dec(${_ffxivparty[${i}].id})}" ExpressionTypeL="Numeric" ExpressionR="${numeric:hex2dec(${_ffxivparty[${j}].id})}" ExpressionTypeR="Numeric" ConditionType="NumericLess" />
              <ConditionSingle Enabled="true" ExpressionL="${i}" ExpressionTypeL="Numeric" ExpressionR="1" ExpressionTypeR="Numeric" ConditionType="NumericNotEqual" />
            </Condition>
            <Conditions />
          </Action>
          <Action OrderNumber="12" LogMessageText="Party sort${i}:${numeric:${j}+1}" LogProcess="True" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="LogMessage" Asynchronous="False">
            <Condition Enabled="true" Grouping="Or">
              <ConditionSingle Enabled="true" ExpressionL="${j}" ExpressionTypeL="Numeric" ExpressionR="8" ExpressionTypeR="Numeric" ConditionType="NumericNotEqual" />
            </Condition>
            <Conditions />
          </Action>
          <Action OrderNumber="13" LogMessageText="Party sort${numeric:${i}+1}:2" LogProcess="True" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="LogMessage" Asynchronous="False">
            <Condition Enabled="true" Grouping="Or">
              <ConditionSingle Enabled="true" ExpressionL="${j}" ExpressionTypeL="Numeric" ExpressionR="8" ExpressionTypeR="Numeric" ConditionType="NumericEqual" />
            </Condition>
            <Conditions />
          </Action>
        </Actions>
        <Condition Enabled="false" Grouping="Or" />
        <Conditions />
      </Trigger>
      <Trigger Enabled="true" Sequential="True" IsReadme="True" Name="设定FFXIV职业顺序" Id="dbe518da-4c7c-47bd-98f0-89e97fb6c746" RegularExpression="设定FFXIV职业顺序" Description="该列表变量按照jobid顺序输入，输入的值为默认游戏内职业排序。&#xD;&#xA;剑术师	GLA	1	1&#xD;&#xA;格斗家	PGL	2	8&#xD;&#xA;斧术师	MRD	3	2&#xD;&#xA;枪术师	LNC	4	9&#xD;&#xA;弓箭手	ARC	5	12&#xD;&#xA;幻术师	CNJ	6	5&#xD;&#xA;咒术师	THM	7	15&#xD;&#xA;刻木匠	CRP	8	19&#xD;&#xA;锻铁匠	BSM	9	20&#xD;&#xA;铸甲匠	ARM	10	21&#xD;&#xA;雕金匠	GSM	11	22&#xD;&#xA;制革匠	LTW	12	23&#xD;&#xA;裁衣匠	WVR	13	24&#xD;&#xA;炼金术士	ALC	14	25&#xD;&#xA;烹调师	CUL	15	26&#xD;&#xA;采矿工	MIN	16	27&#xD;&#xA;园艺工	BTN	17	28&#xD;&#xA;捕鱼人	FSH	18	29&#xD;&#xA;骑士	PLD	19	1&#xD;&#xA;武僧	MNK	20	8&#xD;&#xA;战士	WAR	21	2&#xD;&#xA;龙骑士	DRG	22	9&#xD;&#xA;吟游诗人	BRD	23	12&#xD;&#xA;白魔法师	WHM	24	5&#xD;&#xA;黑魔法师	BLM	25	15&#xD;&#xA;秘术师	ACN	26	16&#xD;&#xA;召唤师	SMN	27	16&#xD;&#xA;学者	SCH	28	6&#xD;&#xA;双剑师	ROG	29	10&#xD;&#xA;忍者	NIN	30	10&#xD;&#xA;机工士	MCH	31	13&#xD;&#xA;暗黑骑士	DRK	32	3&#xD;&#xA;占星术士	AST	33	7&#xD;&#xA;武士	SAM	34	11&#xD;&#xA;赤魔法师	RDM	35	17&#xD;&#xA;青魔法师	BLU	36	18&#xD;&#xA;绝枪战士	GNB	37	4&#xD;&#xA;舞者	DNC	38	14&#xD;&#xA;">
        <Actions>
          <Action OrderNumber="1" ListVariableExpressionType="Numeric" ListVariableName="job_order" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="2" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="1" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="3" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="8" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="4" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="2" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="5" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="9" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="6" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="12" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="7" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="5" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="8" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="15" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="9" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="19" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="10" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="20" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="11" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="21" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="12" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="22" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="13" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="23" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="14" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="24" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="15" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="25" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="16" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="26" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="17" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="27" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="18" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="28" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="19" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="29" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="20" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="1" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="21" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="8" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="22" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="2" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="23" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="9" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="24" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="12" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="25" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="5" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="26" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="15" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="27" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="16" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="28" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="16" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="29" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="6" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="30" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="10" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="31" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="10" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="32" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="13" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="33" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="3" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="34" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="7" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="35" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="11" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="36" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="17" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="37" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="18" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="38" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="4" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="39" ListVariableOp="Push" ListVariableExpressionType="Numeric" ListVariableName="job_order" ListVariableExpression="14" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="ListVariable" Asynchronous="False">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
          <Action OrderNumber="40" LogMessageText="Party sort1:8" LogProcess="True" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="LogMessage">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
        </Actions>
        <Condition Enabled="false" Grouping="Or" />
        <Conditions />
      </Trigger>
      <Trigger Enabled="true" Name="切换区域" Id="978268ab-9eed-47e4-be7e-877c37850b87" RegularExpression="^.{14} 01:Changed Zone">
        <Actions>
          <Action OrderNumber="1" LogMessageText="设定FFXIV职业顺序" LogProcess="True" LogLevel="-1" TextAuraFontSize="9" TextAuraFontName="宋体" ActionType="LogMessage">
            <Condition Enabled="false" Grouping="Or" />
            <Conditions />
          </Action>
        </Actions>
        <Condition Enabled="false" Grouping="Or" />
        <Conditions />
      </Trigger>
    </Triggers>
  </ExportedFolder>
</TriggernometryExport>`

**Comment by pipirapira** [comment]
您好！感谢反馈问题和提供思路。队员排序问题确实一直存在，并且是本项目的一个重点问题。如果您遇到了队员排序功能障碍，在考虑替代方案前，应首先尝试修复插件本身。为此，作者个人建议您检查：
**1.Triggernometry的版本。**
目前已知1.1.3.1版本的Triggernometry中存在队员排序错乱的恶性bug。国服整合版很长一段时间使用1.1.3.1版本的Triggernometry，因此这个问题变成了“国服特有”的一种现象。随着版本更新，这一存在bug的版本将逐渐被替代。关于这一问题的修复，可以参考以下github页面：
https://github.com/paissaheavyindustries/Triggernometry/pull/53
如果您正在使用1.1.3.1版本的Triggernometry，并且需要使用抽卡触发器，或其它需要队员排序的触发器，建议立即更新至1.1.3.5及以上版本，或者您也可以选择由尼尼科技修改的版本。
**2.Triggernometry中的小队列表排序设置**
关于这一点，在说明文档中有详细的设置教程。
**3.FFXIV_ACT_Plugin的版本**
当游戏进行版本更新后，旧版本的FFXIV_ACT_Plugin有可能不再能提供正确的数据来源。因此会出现无法提取队员职业等情况。

在确认以上情况无误以后，抽卡触发器才能正确识别队员列表及其排序。
当然，我们有一些关于版本更新早期，部分插件处于错误状态时如何使用该触发器的研究。目前比较推荐的是使用游戏内置的宏来手动导入队友列表。例如下面的宏，结合特定的触发器，来实现不依赖内建_ffxivparty结构的识别：

> /e #partylist:\<me\>:1:\<targetjob\>:
> /ta \<2\>
> /e #partylist:\<t\>:2:\<targetjob\>:
> /ta \<3\>
> /e #partylist:\<t\>:3:\<targetjob\>:
> /ta \<4\>
> /e #partylist:\<t\>:4:\<targetjob\>:
> /ta \<5\>
> /e #partylist:\<t\>:5:\<targetjob\>:
> /ta \<6\>
> /e #partylist:\<t\>:6:\<targetjob\>:
> /ta \<7\>
> /e #partylist:\<t\>:7:\<targetjob\>:
> /ta \<8\>
> /e #partylist:\<t\>:8:\<targetjob\>:

但由于国服插件的更新速度较快，这样的用法时效性可能不超过开服后3小时，故未作深入研究。
如果您遇到了插件版本不匹配或者插件内存错误之类的情况，请确认您的插件是否是最新版本。

**Comment by SheldonHoo233** [comment]
😂原来是这样的，怪不得国际服没问题，感谢指导~
