### ISSUE TITLE
初始化错误

### ISSUE THREAD

**Issue by skyoffish-ss** [pipirapira/NiNiTechnology#7]
日志信息如下，act版本：肥肥咖啡 FFCAFE 2.19.10.3版，FFXIV_ACT_Plugin版本：2.0.4.0
 ACT.BahamutAnalyser プラグインの初期化で例外が発生しました。
System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 ACT.BahamutAnalyser.FF14PluginHelper.GetCombatantList(Boolean onlyPlayer)
   在 ACT.BahamutAnalyser.BahamutAnalyser.initAll()
   在 ACT.BahamutAnalyser.FF14Watcher.StartLogAnalyseTimer()
   在 ACT.BahamutAnalyser.FF14Watcher.Initialize()
   在 ACT.BahamutAnalyser.BahamutAnalyserPlugin.Advanced_Combat_Tracker.IActPluginV1.InitPlugin(TabPage pluginScreenSpace, Label pluginStatusText)

**Comment by pipirapira** [comment]
感谢反馈。这是由于插件未能正确读取游戏信号导致的初始化错误。新版本中已修复该问题。即使不能读取游戏信号，插件仍将正常启动。

**Comment by skyoffish-ss** [comment]
感谢解答
