### ISSUE TITLE
绝巴哈p2自动标点功能无法使用

### ISSUE THREAD

**Issue by ryzalin** [pipirapira/NiNiTechnology#8]
大佬好，我已经下载了最新版的尼尼科技及paisley park，在尼尼科技的场地标记那一栏中也填入了相应的HTTP port，测试显示连接成功。然而在绝巴哈那一栏中勾选p2俯冲自动场地标点后却无法生效，而且勾选p2俯冲报安全点后，有的时候也会不报安全点。其中场地标点即便tts报了安全点也不会生效。想请问一下是什么问题。

**Comment by pipirapira** [comment]
请将插件日志贴出来或者发送给我以确定问题。
在你打开插件时，会看到如下信息：
正在初始化...
日志文件：C:\Users\Administrator\AppData\Roaming\anoyetta\ACT\ACT.BahamutAnalyser.log
这就是日志文件的地址。如果你能找到当时无法工作的日志文件，请将它尽可能完整地发送给我。

**Comment by ryzalin** [comment]
> 请将插件日志贴出来或者发送给我以确定问题。
> 在你打开插件时，会看到如下信息：
> 正在初始化...
> 日志文件：C:\Users\Administrator\AppData\Roaming\anoyetta\ACT\ACT.BahamutAnalyser.log
> 这就是日志文件的地址。如果你能找到当时无法工作的日志文件，请将它尽可能完整地发送给我。

[ACT.BahamutAnalyser.log](https://github.com/pipirapira/NiNiTechnology/files/3854405/ACT.BahamutAnalyser.log)
这是今天晚上打的，请忽视最开始的四人本_(:з」∠)_，谢谢大佬。

**Comment by pipirapira** [comment]
已确认是标点错误导致插件线程崩溃的问题，在新版本中修复。
但该修复不排除标点错误产生的可能性。请检查paisley park是否为国服对应版本。
最简单的测试方式：
在场地标4个点，并点击插件中的“获取当前标点”，观察坐标值是否发生改变。
如果全部为：
/e /waymark a off
/e /waymark b off
/e /waymark c off
/e /waymark d off
/e /waymark 1 off
/e /waymark 2 off
/micon A waymark
说明无法获得当前的标点，请再次检查paisley park是否为国服对应版本。**国服版本的paisley park插件提示更新，请不要更新。**
另，为方便下载，在项目文件中附带了paisley park的最新版本。

**Comment by ryzalin** [comment]
> 已确认是标点错误导致插件线程崩溃的问题，在新版本中修复。
> 但该修复不排除标点错误产生的可能性。请检查paisley park是否为国服对应版本。
> 最简单的测试方式：
> 在场地标4个点，并点击插件中的“获取当前标点”，观察坐标值是否发生改变。
> 如果全部为：
> /e /waymark a off
> /e /waymark b off
> /e /waymark c off
> /e /waymark d off
> /e /waymark 1 off
> /e /waymark 2 off
> /micon A waymark
> 说明无法获得当前的标点，请再次检查paisley park是否为国服对应版本。**国服版本的paisley park插件提示更新，请不要更新。**
> 另，为方便下载，在项目文件中附带了paisley park的最新版本。

感谢大佬！已经可以用了。
